---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube2iam
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube2iam
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube2iam
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube2iam
subjects:
- kind: ServiceAccount
  name: kube2iam
  namespace: default
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  generation: 1
  labels:
    app: kube2iam
  name: kube2iam
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: kube2iam
  template:
    metadata:
      labels:
        name: kube2iam
    spec:
      containers:
      - args:
        - --auto-discover-base-arn
        - --host-interface=eni+
        - --host-ip=$(HOST_IP)
        - --iptables=true
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: jtblin/kube2iam:0.10.4
        imagePullPolicy: IfNotPresent
        name: kube2iam
        ports:
        - containerPort: 8181
          hostPort: 8181
          name: http
          protocol: TCP
        securityContext:
          privileged: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      serviceAccountName: kube2iam
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
