apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: controlplanes.cluster.eks.amazonaws.com
spec:
  group: cluster.eks.amazonaws.com
  names:
    kind: ControlPlane
    plural: controlplanes
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterName:
              type: string
            version:
              type: string
          required:
          - clusterName
          type: object
        status:
          properties:
            certificateAuthorityData:
              type: string
            endpoint:
              type: string
            status:
              type: string
          required:
          - certificateAuthorityData
          - endpoint
          - status
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
