apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: statefulsets.components.eks.amazonaws.com
spec:
  group: components.eks.amazonaws.com
  names:
    kind: StatefulSet
    plural: statefulsets
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            cluster:
              type: string
            name:
              type: string
            namespace:
              type: string
            podManagementPolicy:
              type: string
            replicas:
              format: int32
              type: integer
            revisionHistoryLimit:
              format: int32
              type: integer
            selector:
              type: object
            serviceName:
              type: string
            template:
              type: object
            updateStrategy:
              type: object
            volumeClaimTemplates:
              items:
                type: object
              type: array
          required:
          - selector
          - template
          - serviceName
          - cluster
          - name
          - namespace
          type: object
        status:
          properties:
            collisionCount:
              format: int32
              type: integer
            conditions:
              items:
                type: object
              type: array
            currentReplicas:
              format: int32
              type: integer
            currentRevision:
              type: string
            observedGeneration:
              format: int64
              type: integer
            readyReplicas:
              format: int32
              type: integer
            replicas:
              format: int32
              type: integer
            status:
              type: string
            updateRevision:
              type: string
            updatedReplicas:
              format: int32
              type: integer
          required:
          - replicas
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
