apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: ingresses.components.eks.amazonaws.com
spec:
  group: components.eks.amazonaws.com
  names:
    kind: Ingress
    plural: ingresses
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            backend:
              type: object
            cluster:
              type: string
            name:
              type: string
            namespace:
              type: string
            rules:
              items:
                type: object
              type: array
            tls:
              items:
                type: object
              type: array
          required:
          - cluster
          - name
          - namespace
          type: object
        status:
          properties:
            loadBalancer:
              type: object
            status:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
