apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: services.components.eks.amazonaws.com
spec:
  group: components.eks.amazonaws.com
  names:
    kind: Service
    plural: services
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            cluster:
              type: string
            clusterIP:
              type: string
            externalIPs:
              items:
                type: string
              type: array
            externalName:
              type: string
            externalTrafficPolicy:
              type: string
            healthCheckNodePort:
              format: int32
              type: integer
            loadBalancerIP:
              type: string
            loadBalancerSourceRanges:
              items:
                type: string
              type: array
            name:
              type: string
            namespace:
              type: string
            ports:
              items:
                type: object
              type: array
            publishNotReadyAddresses:
              type: boolean
            selector:
              type: object
            sessionAffinity:
              type: string
            sessionAffinityConfig:
              type: object
            type:
              type: string
          required:
          - cluster
          - name
          - namespace
          type: object
        status:
          properties:
            loadBalancer:
              type: object
            status:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
