apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: daemonsets.components.eks.amazonaws.com
spec:
  group: components.eks.amazonaws.com
  names:
    kind: DaemonSet
    plural: daemonsets
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            cluster:
              type: string
            minReadySeconds:
              format: int32
              type: integer
            name:
              type: string
            namespace:
              type: string
            revisionHistoryLimit:
              format: int32
              type: integer
            selector:
              type: object
            template:
              type: object
            updateStrategy:
              type: object
          required:
          - selector
          - template
          - cluster
          - name
          - namespace
          type: object
        status:
          properties:
            collisionCount:
              format: int32
              type: integer
            conditions:
              items:
                type: object
              type: array
            currentNumberScheduled:
              format: int32
              type: integer
            desiredNumberScheduled:
              format: int32
              type: integer
            numberAvailable:
              format: int32
              type: integer
            numberMisscheduled:
              format: int32
              type: integer
            numberReady:
              format: int32
              type: integer
            numberUnavailable:
              format: int32
              type: integer
            observedGeneration:
              format: int64
              type: integer
            status:
              type: string
            updatedNumberScheduled:
              format: int32
              type: integer
          required:
          - currentNumberScheduled
          - numberMisscheduled
          - desiredNumberScheduled
          - numberReady
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
