apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: serviceaccounts.components.eks.amazonaws.com
spec:
  group: components.eks.amazonaws.com
  names:
    kind: ServiceAccount
    plural: serviceaccounts
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            apiVersion:
              type: string
            automountServiceAccountToken:
              type: boolean
            cluster:
              type: string
            imagePullSecrets:
              items:
                type: object
              type: array
            kind:
              type: string
            metadata:
              type: object
            name:
              type: string
            namespace:
              type: string
            secrets:
              items:
                type: object
              type: array
          required:
          - cluster
          - name
          - namespace
          type: object
        status:
          properties:
            status:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
