apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: configmaps.components.eks.amazonaws.com
spec:
  group: components.eks.amazonaws.com
  names:
    kind: ConfigMap
    plural: configmaps
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            binaryData:
              type: object
            cluster:
              type: string
            data:
              type: object
            name:
              type: string
            nameSpace:
              type: string
          required:
          - cluster
          - name
          - nameSpace
          type: object
        status:
          properties:
            status:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
