apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: customresourcedefinitions.components.eks.amazonaws.com
spec:
  group: components.eks.amazonaws.com
  names:
    kind: CustomResourceDefinition
    plural: customresourcedefinitions
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            additionalPrinterColumns:
              items:
                type: object
              type: array
            cluster:
              type: string
            group:
              type: string
            name:
              type: string
            names:
              type: object
            namespace:
              type: string
            scope:
              type: string
            subresources:
              type: object
            validation:
              type: object
            version:
              type: string
            versions:
              items:
                type: object
              type: array
          required:
          - group
          - names
          - scope
          - cluster
          - name
          - namespace
          type: object
        status:
          properties:
            acceptedNames:
              type: object
            conditions:
              items:
                type: object
              type: array
            status:
              type: string
            storedVersions:
              items:
                type: string
              type: array
          required:
          - conditions
          - acceptedNames
          - storedVersions
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
