apiVersion: components.eks.amazonaws.com/v1alpha1
kind: CustomResourceDefinition
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: customresourcedefinition-sample
spec:
  # Add fields here
  foo: bar
